### ISSUE TITLE
Failed at step EXEC spawning /usr/local/bin/otelcol-contrib: No such file or directory

### ISSUE THREAD

**Issue by laiyunong** [open-telemetry/opentelemetry-collector-releases#106]
RPM packaging for Linux amd64
otelcol-contrib_0.47.0_linux_amd64.rpm cannot start

**Comment by SaschaBrechmannVHV** [comment]
Hi @laiyunong ,
the path to the binary has changed. it is now /usr/bin/otelcol-contrib .
Regards, Sascha

**Comment by jpkrohling** [comment]
There was a bug in an earlier version, fixed later on. Let me know if you still experience this with the latest version.
