### ISSUE TITLE
collector does not include nginx receiver

### ISSUE THREAD

**Issue by nslaughter** [open-telemetry/opentelemetry-collector-releases#108]
**Describe the bug**

The collector does not include the nginx receiver, which you'll notice if you configure `nginx` among receivers.

**Steps to reproduce**

Add an entry for `nginx:` to receivers in the collector's config `.yaml`

**What did you expect to see?**

Successful run of the collector returning metrics for nginx when configuration is right for the environment or reporting on other aspects of configuration.

**What did you see instead?**

It logs `Error: failed to get config: cannot unmarshal the configuration: unknown receivers type "nginx" for "nginx" (valid value s: [statsd awscontainerinsightreceiver ...`.

**What version did you use?**

v0.49.0

**What config did you use?**

``` yaml
receivers:
  nginx:
```

**Environment**

Docker images `golang:1.17` and `golang:latest`

**Additional context**

- I have made changes to code that resolves the issue by adding the nginxreceiver factory to the list of receivers in `internal/components/components.go`
- There's also a test file where we need to add a reference to the nginx receiver.
- And there are some administrative items to be handled for the build such as adding the nginxreceiver package to the go.mod in the root and in cmd/configschema. Additionally we need replace directives in the go.mod fils to use the relative path for nginxreceiver.

**Comment by jpkrohling** [comment]
Looks like it's missing from the manifest: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml

**Comment by nslaughter** [comment]
@jpkrohling I understand that this issue means the manifest needs to be updated, but could you explain why the issue should be on the opentelemetry-collector-releases repo? Thank you.

**Comment by jpkrohling** [comment]
The manifest resides here, in the -releases repository.

**Comment by TylerHelmuth** [comment]
I think the issue is bigger than the manifest.  As @nslaughter mentioned, the factory isn't setup in [components.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/components/components.go).  Without the factory I don't think the component can get made.

**Comment by jpkrohling** [comment]
The components.go isn't used in the distribution. A new one is generated by the builder:

https://github.com/open-telemetry/opentelemetry-collector/blob/b34df3a7e7e9ea6dba20608c2f1f53bedc2a3d22/cmd/builder/internal/builder/main.go#L67

**Comment by nslaughter** [comment]
> ... the components.go from that repository isn't used in the distribution. A new one is generated by the builder ...

Thank you for explaining. I was missing that.

Should I plan to open another PR here in releases after the one in contrib can be merged?

**Comment by djaglowski** [comment]
Thanks @nslaughter.

@jpkrohling, is there a heuristic for which components should be added to contrib's components.go? 

Based on the guidelines established in [contrib#9412](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9412), perhaps we should eventually expect that contrib's `components.go` and the corresponding manifest in this repo should both contains all components that are [Alpha or higher](https://github.com/open-telemetry/opentelemetry-collector-contrib#stability-levels).

**Comment by TylerHelmuth** [comment]
I agree, if it's not "in development" anymore it should be included in distributions and contrib's local execution.
