### ISSUE TITLE
Remove newrelicexporter

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-releases#119]
Follow up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9894

https://github.com/open-telemetry/opentelemetry-collector-releases/blob/c91fef72b696ed4d4a666929cb72c4fba05f6fff/distributions/otelcol-contrib/manifest.yaml#L63

**Comment by bogdandrutu** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-releases/pull/120
