### ISSUE TITLE
Install collector script

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-collector-releases#136]
Via https://github.com/open-telemetry/opentelemetry.io/pull/1333, based on @chalin's suggestion to have this hosted here: 

While [updating the collector getting started](https://github.com/open-telemetry/opentelemetry.io/pull/1332), I played around with the different ways of getting a collector up and running. Pulling and running it through a docker container is definitely the most convenient way but it comes with plenty of overhead and sometimes I just want to have a collector running on my laptop. This requires a few clicks right now (and you need to read closely because arm64 and amd64 are hard to distinguish), so I thought, why not have a similar install experience as brew or nvm:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-releases/HEAD/install/otel-contrib.sh)"
./otelcol --config config.yml
```

The `install.sh` looks like the following: https://raw.githubusercontent.com/open-telemetry/opentelemetry.io/6e5511b10d6ae91c28691dbd17fad9e6a96a123f/content/en/install/otelcol-contrib.sh

or in a video:

https://user-images.githubusercontent.com/1519757/169013228-6fbb3835-80ba-4972-886a-1a645c78908b.mp4

what do you think, something OTel needs? :-)

**Comment by jpkrohling** [comment]
Call me old-fashioned, but I shiver every time I see bash with curl. I personally prefer to get the RPM which would keep my binary up to date (like for kubectl or minikube). When that's not available, a simple RPM is what I prefer. After that, I get the binary and manage it via "alternatives".

But I do understand that some people prefer bash with curl, so, I wouldn't be against it if we have enough people interested in using and maintaining this script.

**Comment by svrnm** [comment]
I agree that from a security perspective this requires a lot of trust by the end user in that URL being benign. Although the goal of this script is serving people that get started with OpenTelemetry and just want to get the touch&feel of the collector quickly. In a production environment it's definitely not the right tool.

**Comment by svrnm** [comment]
Doesn't look like there's a lot of interest, closing.
