### ISSUE TITLE
v0.45.1 release tag and assets missing

### ISSUE THREAD

**Issue by prashant-shahi** [open-telemetry/opentelemetry-collector-releases#150]
We can see `v0.45.1` release in https://github.com/open-telemetry/opentelemetry-collector-contrib repository:

https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.45.1

**Comment by codeboten** [comment]
@prashant-shahi the decision was made not to create a binary release of that version, it was a patch release to address an issue in a go.mod file, see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7959#issuecomment-1044669348 for more details.

Is there something specific in v0.45.1 that isn't part of either v0.45.0 or v0.46.0 that you have a need for?

**Comment by prashant-shahi** [comment]
> Is there something specific in v0.45.1 that isn't part of either v0.45.0 or v0.46.0 that you have a need for?

@codeboten nothing in specific. Just that found weird for one patch release to not have any binary release.
But yeah, I suppose upgrading to v0.46.0 should not be any problem. 

Thanks for responding :)

**Comment by codeboten** [comment]
Thanks for following up!
