### ISSUE TITLE
Windows MSI

### ISSUE THREAD

**Issue by HaroonSaid** [open-telemetry/opentelemetry-collector-releases#157]
Is there a windows msi installer release for the collector?

**Comment by jpkrohling** [comment]
Done

**Comment by dodegaard** [comment]
@jpkrohling I may be willing to research this and work on this.  What is the build system used to create the releases? GitHub Actions seems to have a ton of steps defined.

**Comment by jpkrohling** [comment]
We use goreleaser for automating our build. Look at .goreleaser.yaml at the root of this repository, and goreleaser.io for more information about the tool itself. 

Our .goreleaser.yaml is auto-generated, but I'd recommend playing directly with that file at first, and then bringing the changes back to the Go files that generate it (cmd/goreleaser/internal/configure.go)

**Comment by smithclay** [comment]
Hey, just one quick note/good news: looks like goreleaser pro (version this repo uses) supports creating MSIs:

https://goreleaser.com/customization/msi/

**Comment by jpkrohling** [comment]
Creating it is the easy part, maintaining is something more: it requires people who'd be willing to take care of bug reports. Ideally, that would be a maintainer, but if someone active enough volunteers to take care of this build, I think we can give it a try.

**Comment by mx-psi** [comment]
Would be great to have someone with Windows expertise listed on here https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/platform-support.md#tier-2--secondary-support

**Comment by pjanotti** [comment]
@mx-psi I volunteer myself for tier 2 support for Windows/amd64

**Comment by mx-psi** [comment]
Awesome! I am in favor of proceeding with this then :) cc @open-telemetry/collector-contrib-approvers

**Comment by TylerHelmuth** [comment]
Let's start by updating https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions#criteria-for-supported-distributions

**Comment by astencel-sumo** [comment]
> Let's start by updating https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions#criteria-for-supported-distributions

What exactly should be updated there @TylerHelmuth? Do you mean to add the requirement to build Windows MSI package to point 7.?

Btw. to be honest I'm surprised that the requirement for brew packages is there - I don't think we publish brew packages for Otelcol core or contrib at all? Here's a related issue I found:
- https://github.com/open-telemetry/opentelemetry-collector/issues/7891.

**Comment by astencel-sumo** [comment]
>  lets update 7 to say Windows MSIs are allowed.

You're saying "allowed" but point 7 uses the word "must":

> Must include the following assets (...) [unless] clearly stated which assets are skipped and why

I'll add Windows MSI to that list for now, we can separately consider if we should rephrase this point to make it less demanding. We currently don't provide brew or MSI for any distro.

**Comment by TylerHelmuth** [comment]
Ya maybe this doesn't need updated because of that line, but I think if we're gonna support Windows providing an MSI as an expectation unless otherwise specified makes sense.

**Comment by astencel-sumo** [comment]
- https://github.com/open-telemetry/opentelemetry-collector-releases/pull/501

**Comment by briantist** [comment]
I would also love to see MSI support. I have built MSIs before and added support for them to existing projects, though it sounds like that won't be needed manually since you have a version of goreleaser with built-in support which is great.

**Comment by pjanotti** [comment]
Four aspects that come to my mind related to releasing an MSI:

1. MSI design: we need to agree on the install settings and of the MSI. I suppose it installs the collector as a Windows service running as LocalSystem and brings a default configuration file installed to `%ProgramData%`, the collector is installed machine-wide (i.e.: not per user installation), does NOT support side-by-side installs, etc.
2. Tool(s) to build MSI: the preference is to go with whatever `goreleaser` offers, but, we should do due diligence and investigate the available options and respective pros and cons.
3. Signing: there was an old issue regarding singing the exe but no resolution, see https://github.com/open-telemetry/opentelemetry-collector-releases/issues/169. Ideally we should sign the shipped binaries and the MSI itself.
4. Builder support: this is out of scope in the near term, but, I would like to check if there is interest in adding this support to the builder some time after we have the MSI.

I’m planning to go ahead and open a new item on the collector repo to discuss item 1 and we can keep the conversation about 2 here.

**Comment by mx-psi** [comment]
I am going to revert #560 on #570, thus I am reopening this issue

**Comment by mx-psi** [comment]
On a new version of this PR, we should ensure the tests in PR actually test that producing an MSI works in an actual release.

**Comment by pjanotti** [comment]
@mx-psi @jpkrohling there are two follow-ups, mentioned in the original #560 description, that I'm planning to do in a near future:

1. MSI smoke tests: I would like to add some golang tests for the MSI doing the basic stuff: install/uninstall and validate the configuration. Currently, there are no tests running on the releases repository - it will be simpler to just add the tests to this repository.
1. The `windows-installer.wxs` and `opentelemetry.ico` are duplicated on the `otelcol` and `otelcol-contrib` folders, they are exactly the same. I will look at generating at least the `wxs` file, either in this repo or by adding it as an option to the builder, to avoid this duplication.

We can close the present issue now or wait for a successful release of the MSIs.

**Comment by briantist** [comment]
> MSI smoke tests: I would like to add some golang tests for the MSI doing the basic stuff: install/uninstall and validate the configuration. Currently, there are no tests running on the releases repository - it will be simpler to just add the tests to this repository.

@pjanotti I agree, I've written tests for MSI builds before in CI (GitHub Actions), it's important to test install, uninstall, reinstall, upgrade, etc. After the first release with an MSI it's possible to test for example, upgrading from current latest.

Here is an older example:
- https://github.com/briantist/CcgVault/blob/main/.github/workflows/_test.yml

I did more extensive work last year for another project based on this but it's in a private repository and I can't share it, above still covers the gist of it.

The tests themselves happen to be written in Pester since PowerShell is convenient for testing the things that needed testing, but they don't have to be.
- https://github.com/briantist/CcgVault/blob/main/test/integration/MSI.Tests.ps1

**Comment by mx-psi** [comment]
@pjanotti Let's either keep this open or open separate issues for the remaining steps

**Comment by pjanotti** [comment]
@mx-psi I opened: 

* #575
* #576

**Comment by mx-psi** [comment]
Awesome, I am closing this was then :)
