### ISSUE TITLE
adding support for power arch ppc64le 

### ISSUE THREAD

**Issue by adilhusain-s** [open-telemetry/opentelemetry-collector-releases#158]
I have successfully built and tested the opentelemetry-collector and opentelemetry-collector-contrib on power vm.  I've also started working on opentelemetry-collector-release to add power support in CICD. I've made the changes in opentelemetry-collector-releases and generated the binaries and docker images for power. 
here is the draft PR for the same. 
[draft PR link] (https://github.com/open-telemetry/opentelemetry-collector-releases/pull/156)

could someonse please give me any suggestions /comments on my pr?

**Comment by jpkrohling** [comment]
Before we add this here, both the collector core and contrib should include this architecture in the CI. Otherwise, things will eventually break here and we'll catch only during the release procedure.

**Comment by adilhusain-s** [comment]
thanks for the response,

that makes sense. I'll start working on collector-core and collector-contrib.

**Comment by adilhusain-s** [comment]
@jpkrohling
are we talking about  the only release pipeline or build and test as well?
I've just checked the repo of collector-core and I can't find any build-test pipeline for arm64.

**Comment by jpkrohling** [comment]
There's a "cross-build-and-test" target that you can use: https://github.com/open-telemetry/opentelemetry-collector/runs/7219627797?check_suite_focus=true
