### ISSUE TITLE
Release binaries and images for v0.56.0

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-releases#166]

**Comment by yuriolisa** [comment]
@dmitryax, are the packages available? I think not yet, correct?

```
docker pull ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.55.0
0.55.0: Pulling from open-telemetry/opentelemetry-collector-releases/opentelemetry-collector
b0d129412ef7: Pull complete
075e2f0b63fc: Pull complete
4ae5496f171e: Pull complete
Digest: sha256:2f62c46a2f748fa900c6d943c6883e86716853bcfd814df215d5b66944db29b5
Status: Downloaded newer image for ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.55.0
ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.55.0

docker pull ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.56.0
Error response from daemon: manifest unknown
```

**Comment by amoscatelli** [comment]
non-contrib images are missing too 

https://hub.docker.com/r/otel/opentelemetry-collector/tags

**Comment by codeboten** [comment]
@yuriolisa @amoscatelli those images will be available once this issue is closed.

**Comment by dmitryax** [comment]
Hey folks. Sorry for the delay. Binaries building is in progress https://github.com/open-telemetry/opentelemetry-collector-releases/runs/7453336092?check_suite_focus=true

**Comment by amoscatelli** [comment]
@dmitryax it seams something went wrong ...

#5 [certs 2/2] RUN apk --update add ca-certificates
#5 0.839 standard_init_linux.go:228: exec user process caused: exec format error
#5 ERROR: executor failed running [/bin/sh -c apk --update add ca-certificates]: exit code: 1

**Comment by dmitryax** [comment]
I'm looking into that

**Comment by dmitryax** [comment]
packages and images for 0.56.0 are released
