### ISSUE TITLE
etc/os-release is not copied to final image

### ISSUE THREAD

**Issue by assafrahav** [open-telemetry/opentelemetry-collector-releases#175]
GCP [container analysis services](https://cloud.google.com/container-analysis/docs/container-scanning-overview#linux-versions) which perform vulnerability scans of images used in conjunction with GKE uses `etc/os-release` to determine the OS of the image.

otel collector does use Alpine 3.11 which is a supported base image, but the specific file isn't copied into the final image so the service is unable to scan it.

Could you add this step (ideally to all otel images) so that they are able to be scanned?

**Comment by sherzberg-1** [comment]
I'll also note that I believe this is a common practice with vulnerability scanners - trivy is also unable to scan this container, with the error message `2022-07-29T17:05:44.773Z        WARN    This OS is not supported and vulnerabilities in OS packages are not detected.`

**Comment by iblancasa** [comment]
I can work on it :)

**Comment by jpkrohling** [comment]
It's yours, @iblancasa

**Comment by mx-psi** [comment]
> otel collector does use Alpine 3.11 which is a supported base image, but the specific file isn't copied into the final image so the service is unable to scan it.


The OpenTelemetry Collector container images do **not** use Alpine 3.11 as the base image; they are built ['from scratch'](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/8b0b4b6f95a2b1c4e02c80f7c7b61f9e95054947/distributions/otelcol-contrib/Dockerfile#L4). Alpine is used as the first part of a [multi-stage build](https://docs.docker.com/build/building/multi-stage/), with the only file from it present in the final container image being `/etc/ssl/certs/ca-certificates.crt` (a certificate bundle to support TLS connections). Adding `/etc/os-release` to container images would result in false positives so I think we should not do it.

**Comment by mx-psi** [comment]
Closing as wontfix, since this is a nonissue. If you believe my comment above is wrong please comment so that we can reopen this :)
