### ISSUE TITLE
Images don't pass the vulnerability scan

### ISSUE THREAD

**Issue by piotrgwiazda** [open-telemetry/opentelemetry-collector-releases#178]
Due to the fact that images are not based on any distro - with `FROM scratch` they will not pass vulnerability scan, as there is no distro for searching in vulnerability database (base image unknown).

Please provide images based on e.g. alpine if possible.

**Comment by jpkrohling** [comment]
Tracked as part of #175. If this is not the same issue, please provide more details on what needs to be changed to pass the scans.

**Comment by piotrgwiazda** [comment]
When using the Sysdig scanner the scan fails with the "vulnerability_data_unavailable" error.
Message: "Feed data unavailable, cannot perform CVE scan for distro: Unknown:0"

I guess the "distro: Unknown: 0" part is the problem.

**Comment by jpkrohling** [comment]
That still doesn't tell us what we should do to address this.

**Comment by piotrgwiazda** [comment]
How about building alternative image with *-alpine tag that is built on top of alpine distro rather than "FROM scratch"? So one can pick either a slim, distroless image or alpine-based image.
