### ISSUE TITLE
Allow customization of properties

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-releases#18]
The script that generates go-releaser files makes assumptions that are not always true. For instance, the container image for the core distribution defaults to "otel/otelcol:v0.35.0", when it should in fact use "otel/opentelemetry-collector:0.35.0"

**Comment by codeboten** [comment]
This may have already been answered at some point, but is there any possibility to use the `opentelemetry` docker org? That way the name could just be `opentelemetry/collector`. Not sure if we know who owns that docker org though.

**Comment by jpkrohling** [comment]
I think people tried to get handle of that org on Docker Hub but were unable to do so: https://github.com/open-telemetry/community/issues/164
