### ISSUE TITLE
Automatic PR for docs to bump collector version

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-collector-releases#196]
the collector getting started at opentelemetry.io has a variable `collectorVersion` that controls the version used through out the document: 

https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/collector/getting-started.md

We are currently bumping that version manually from time to time and missed some of the collector releases!

Since we had a similar discussion with the [java SIG](https://github.com/open-telemetry/opentelemetry.io/pull/1759), I was wondering if we could implement a trigger that raises a PR on release, like @trask has it:

https://github.com/open-telemetry/opentelemetry-java/pull/4765
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6650

cc @cartermp

**Comment by jpkrohling** [comment]
While we could do that, I think it would scale better to have a script that runs periodically on your side and checks for new releases, bumping the files that need to be changed. I have something similar here:

https://github.com/grafana/opentelemetry-collector-components/blob/main/.github/workflows/auto-update.yaml

**Comment by trask** [comment]
oh, I like this idea, may try it out in the Java repos, would avoid needing the bot to have its own fork in order to open PRs

**Comment by svrnm** [comment]
Then let's do it the otherway round and have the opentelemetry.io repo take new updates periodically (same for java and other projects that need a regular update), cc: @cartermp , @chalin

**Comment by svrnm** [comment]
I gave it a try at @ https://github.com/open-telemetry/opentelemetry.io/pull/1838

**Comment by jpkrohling** [comment]
I'm closing this in favor of doing it on the consumer side of things (opentelemetry.io). If you prefer to keep this open, let me know and I'll reopen.
