### ISSUE TITLE
Collector startup fails with no useful error if invalid pipeline type is specified

### ISSUE THREAD

**Issue by AlexPSplunk** [open-telemetry/opentelemetry-collector-releases#199]
I created a pipeline of type "metric", purposely omitting the "s" from the end of the line.  The collector failed to start, as expected.  However, there is no useful error message in the journal -- it just says "exit code".  See attached screenshot.
(Note: these are the same messages that appear in the system journal.  There is nothing more there)

Would be preferable to provide a useful error message, such as "metric" is not a supported pipeline type.

Setup:  Running the Splunk distribution of the OpenTelemetry collector
otelcol version v0.58.0
Running on Linux:  5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

![invalid pipeline type no error message](https://user-images.githubusercontent.com/66703262/191617708-cafb5ceb-b0d1-42d5-b2ea-b2e19dbdb1dd.png)

**Comment by jpkrohling** [comment]
Using either the project's official OpenTelemetry Collector core distribution or the Contrib distribution instead of Splunk's.

**Comment by mx-psi** [comment]
I am going to close this given the lack of response. If you want to reopen please comment below.
