### ISSUE TITLE
running as a windows services

### ISSUE THREAD

**Issue by TimmyGilissen** [open-telemetry/opentelemetry-collector-releases#214]
I'm using nssm to install the otel collector as a windows service.

But every-time the service wants to start it goes in pauze mode.

What i'm i missing to install the collector as a windows service?

Using collector version 0.60.0.

thx
Timmy

**Comment by elitistphoenix** [comment]
I'd be interested to know how it installs the service? Maybe a windows registry screenshot? I can't get the service to start from a new-service command in powershell

**Comment by codeboten** [comment]
@elitistphoenix if you're running into issues w/ v0.63.0, it's possibly related to https://github.com/open-telemetry/opentelemetry-collector/issues/6433

**Comment by jpkrohling** [comment]
I don't think we have any maintainers using Windows, we need your input and engineering help to determine what's the cause and how to fix it.

**Comment by Outek** [comment]
I'll try to implement this, we have already some go apps which we install as service on windows.

**Comment by TimmyGilissen** [comment]
@Outek that would be awesome thx!

**Comment by simcot** [comment]
I'd be interested to know if @Outek had any success in turning the Otel collector into a  windows service as I find myself in the position of using a service creation tool like NSSM 🙏

**Comment by PedroMcj** [comment]
Hey @simcot I think I've run into the same problem when using NSSM. After adding the env variable "NO_WINDOWS_SERVICE=1" (as mentioned [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#startup-failing-in-windows-docker-containers) ) to the configuration on NSSM, the new service started correctly. Hope this helps!

**Comment by pjanotti** [comment]
@open-telemetry/collector-maintainers I didn't test this on NSSM, I'm not familiar with it, but, I think we can close this one, since detection to run as a service was fixed via #9042

**Comment by mx-psi** [comment]
Closing, please file a new issue if you have trouble with running the Collector as a Windows service
