### ISSUE TITLE
`servicegraph` Processor not included

### ISSUE THREAD

**Issue by sherifkayad** [open-telemetry/opentelemetry-collector-releases#217]
It seems like the Service Graph Processor (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/servicegraphprocessor) isn't included in the `contrib` distro. Is that by mistake? Was that intentional?

I think it should be included as it's officially released in the contrib source code since `v0.60.0` (https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.60.0)

With image version 0.61.0 of the contrib collector I am getting:
```
collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown processors type \"servicegraph\" for \"servicegraph\" (valid values: [cumulativetodelta resourcedetection resource memory_limiter attributes k8sattributes experimental_metricsgeneration probabilistic_sampler spanmetrics transform batch deltatorate filter groupbytrace metricstransform span groupbyattrs redaction routing tail_sampling])\n
```

**Comment by TylerHelmuth** [comment]
Sometimes components that are still in "In Development" status aren't included in the distribution yet. It's normally up to the component code owners if they want it included yet or not.

**Comment by sherifkayad** [comment]
@TylerHelmuth thanks for the feedback. I submitted another issue in the `opentelemtry-collector-contrib` project to ask the same. Hopefully the code owners can give an answer on at least when it would be included.

**Comment by codeboten** [comment]
This component is now in the contrib distro. Adding any component is something that's supported through a custom manifest. Closing this issue for now, please open a new issue if a `dev` release is something that's desirable.
