### ISSUE TITLE
Add promtail receiver to contrib v0.70.0

### ISSUE THREAD

**Issue by viniciusmuller** [open-telemetry/opentelemetry-collector-releases#272]
Would it be possible to add the promtail receiver to the next release?
[It seems that the issues around it were resolved](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16722), so I wonder if a pull request adding it here would be welcome

Ping @mar4uk

**Comment by codeboten** [comment]
The promtail receiver was removed due to issues w/ dependencies https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18524.
