### ISSUE TITLE
goreleaser with --snapshot attempts to push docker images

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-releases#288]
The latest version of goreleaser attempts to push docker images even with snapshot enabled, which should in theory avoid publishing any artifacts. See for more details on the failure:

https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/4131417491/jobs/7139027466

**Comment by codeboten** [comment]
Here's a previous build which didn't try to push docker images: https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/3877683687/jobs/6612988107

**Comment by jpkrohling** [comment]
Opened https://github.com/goreleaser/goreleaser/issues/3771 to track this.

**Comment by codeboten** [comment]
Thanks @jpkrohling!

**Comment by codeboten** [comment]
Should be fixed by https://github.com/open-telemetry/opentelemetry-collector-releases/pull/301
