### ISSUE TITLE
review replaces statements in the manifest

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-releases#29]
Are these replaces needed anymore?  Now that we're using `multimod` to manage versions in require statements we might be able to omit these.  Perhaps something to try after this release is shipped.

_Originally posted by @Aneurysm9 in https://github.com/open-telemetry/opentelemetry-collector-releases/pull/28#r730172874_

**Comment by jpkrohling** [comment]
The `replaces` have been removed. Closing.
