### ISSUE TITLE
docker_observer

### ISSUE THREAD

**Issue by eratio08** [open-telemetry/opentelemetry-collector-releases#314]
Hello, as I [learned](https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/20318) the [`docker_observer`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/observer/dockerobserver) is currently not included in the [otel/opentelemetry-collector-contrib:latest
](otel/opentelemetry-collector-contrib:latest) Docker image (not included in the [manifest.yaml](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml)).

Is there any chance that it could be included in future releases?

Thanks in advance.

**Comment by jpkrohling** [comment]
cc @MovieStoreGuy as the code owner

**Comment by MovieStoreGuy** [comment]
Oh interesting, let me see if I can get that added as part of it.

cc @rmfitzpatrick , @dmitryax

**Comment by dmitryax** [comment]
@eratio08, thanks for reporting. I don't see a reason to not include it
