### ISSUE TITLE
:bug: v0.78.0 Linux assets are missing

### ISSUE THREAD

**Issue by darkweaver87** [open-telemetry/opentelemetry-collector-releases#341]
On last v0.78.0 it looks like your github runner went out of disk space.
Consequently, only 11 assets were created instead of the usual 43.
Thanks :-)

**Comment by codeboten** [comment]
For more info on the disk running out, see https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/5062625852/jobs/9088345803#step:22:7

**Comment by codeboten** [comment]
Discussed this with other maintainers, will break the release process further. Currently the github actions that produce the artifacts are split by GOOS, will split by GOARCH and distribution as well

**Comment by mpostument** [comment]
Hey team, any ETA on linux binary for 0.78.0 version? I am waiting for dynamic index in elastic exporter. But cannot upgrade yet

**Comment by codeboten** [comment]
Artifacts are posted now: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.78.0, closing the issue
