### ISSUE TITLE
goreleaser options need updating

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-releases#343]
--rm-dist has been deprecated in favour or --clean, see https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/5062625852/jobs/9088345803#step:12:21

**Comment by mx-psi** [comment]
Fixed by #342 :)

**Comment by codeboten** [comment]
thanks for pre-fixing my issue @mx-psi  :D
