### ISSUE TITLE
opentelemetry-collector-contrib distribution v0.78.0 is missing syslog exporter

### ISSUE THREAD

**Issue by eloo-abi** [open-telemetry/opentelemetry-collector-releases#348]
Hi,

i was trying to use the syslog exporter released in 0.78.0 contrib but sadly discovered that the exporter is not bundled in the contrib distribution release.

It looks like the import is missing in the manifest file there.

I hope this could be included in the next release.

Best regards
Joseph

**Comment by jpkrohling** [comment]
cc @kkujawa-sumo @rnishtala-sumo @astencel-sumo

**Comment by astencel-sumo** [comment]
The Syslog exporter is currently in development. Here are the issues that need to be resolved before it goes to alpha and gets included in contrib distro:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21245
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21244
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21242
