### ISSUE TITLE
Add support for Linux on IBM Z mainframes and s390x architecture 

### ISSUE THREAD

**Issue by rrschulze** [open-telemetry/opentelemetry-collector-releases#378]
### Description

This is a proposal to add support of Linux on IBM Z and the s390x systems architecture to the OpenTelemetry Collector distributions. The mainframe systems IBM Z and LinuxONE are built on the s390x architecture and are widely used by large enterprises, e.g., in the banking and insurance industry. We see a growing interest of customers but as well from ISVs to explore OpenTelemetry for the mainframe. The support of Linux on IBM Z by the OpenTelemetry Collector distributions will simplify the adoption of OpenTelemetry on the mainframe and enable to drive further observability enhancements for Linux on IBM Z using OpenTelemetry.

### Use Cases

We see three primary use cases:
- Enable end-to-end observability for distributed applications with services and components deployed in public/private cloud environments and on the mainframe.
- Enable customers to use for Linux on IBM Z and the mainframe the same observability products and tools as for other platforms.
- Enable ISVs to support Linux on IBM Z and the mainframe more easily.

### Support ownership
@bwalk-at-ibm and myself (@rrschulze) will take ownership of the OpenTelemetry support for Linux on IBM Z and the s390x architecture. We will continue to maintain contributions for the s390x platform, i.e., act as owners for issues and problems related to Linux on IBM Z and run regularly verifications on s390 VMs.

We will join the Collector SIG meetings starting from Wednesday, August 2, 2023, and following ones.

In preparation of the PRs (core, contrib, releases) for the s390x support of the collector, we followed the instructions on [this page](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/CONTRIBUTING.md#adding-support-for-new-platforms-or-architectures). We tested the qemu-based build on a x86-64 machine and the build results on a s390x VM. In addition, we used and verified the OTel collector on the s390x platform for several scenarios already internally. We plan to submit the PRs  for the s390x support of the collector after discussing in the SIG meeting(s) and will submit an additional PR to update the documentation (e.g., [this page](https://opentelemetry.io/docs/collector/getting-started/)) once the releases support the s390x platform.

**Comment by mx-psi** [comment]
I would like to define support tiers first as I mentioned previously for AIX here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19195#issuecomment-1458560971 Would you be willing to own this part of the process as well? I am happy to work with you on this and review any PRs you open

**Comment by rrschulze** [comment]
@mx-psi yes, I can do that. Let me prepare a proposal and new issue for it.

**Comment by frzifus** [comment]
Hi @rrschulze, AFAIK there are already some QE measures in place to test the OpenShift otel distro on [ppc64le](https://catalog.redhat.com/software/containers/rhosdt/opentelemetry-collector-rhel8/613b50f3a052bb39f2c5f31f?architecture=ppc64le) and [s390x](https://catalog.redhat.com/software/containers/rhosdt/opentelemetry-collector-rhel8/613b50f3a052bb39f2c5f31f?architecture=s390x). Would it help you to reuse parts of it here?

**Comment by mx-psi** [comment]
We have tier 3 support now for `linux/s390x` and the next release will have binaries for this platform :tada: I am going to close this, if we want to increase the tier we can open a separate issue for it.
