### ISSUE TITLE
Add OpenSearch Exporter to the Contrib Manifest

### ISSUE THREAD

**Issue by YANG-DB** [open-telemetry/opentelemetry-collector-releases#390]
## Description

The OpenSearch exporter was recently[ merged](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24540) to the contrib repo 

It is not yet present in the [otel contrib](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib) distrbution

## Additional info
- https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml

````
                 
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/opensearchexporter v0.83.0

````

**Comment by jpkrohling** [comment]
cc code owners @Aneurysm9 @MitchellGale @MaxKsyunz @YANG-DB

**Comment by MaxKsyunz** [comment]
> cc code owners @Aneurysm9 @MitchellGale @MaxKsyunz @YANG-DB

The exporter needs to be add to otelcontribcol. I'll submit a PR for that.
Is there anything else necessary before it can be marked as Alpha?

**Comment by atoulme** [comment]
The CI will fail if you try to move to alpha and miss anything.
