### ISSUE TITLE
Add ARM binaries and images back

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-releases#42]
The ARM binaries and images were first added via #39 and removed via #41. This ticket is to track it being added back once the failures are sorted out.

**Comment by jpkrohling** [comment]
cc @silverlyra

**Comment by silverlyra** [comment]
ah hey, we can close this now 😄 since #55 and [v0.4.3](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.43.0)
