### ISSUE TITLE
Split goreleaser configuration per distribution

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-releases#44]
Even though GoReleaser is fast on local machines, it's really slow at CI. Two distributions with the current matrix of arch/platforms are sufficient to cause the default timeout to happen (30m).

Ideally, we would split the workflows and goreleaser files per distribution.

**Comment by mx-psi** [comment]
Duplicate of #429?

**Comment by jpkrohling** [comment]
I'm closing this in favor of the newer issue, given that it has more information than this here.
