### ISSUE TITLE
Does the collector support win32?

### ISSUE THREAD

**Issue by Narcissus666** [open-telemetry/opentelemetry-collector-releases#442]
I need to collect logs in Windows Server 2008 which system is Win32.
Can I use the open telemetry collector to collect logs?
Which tags can I use?
Thanks!

**Comment by mx-psi** [comment]
I am going to close this as a duplicate of open-telemetry/opentelemetry-collector-contrib/issues/30327, please comment there if you have additional requirements, thanks!
