### ISSUE TITLE
Windows 2008R2 Installation of otel-0.91.0

### ISSUE THREAD

**Issue by Nannymeta** [open-telemetry/opentelemetry-collector-releases#450]
Hello,

I've tried to install otel-0.91.0 on a Windows 2008R2

Error : Exception 0xc0000005 0x8 0x0 0x0 PC=0x0 runtime.asmstdcall()

![image](https://github.com/open-telemetry/opentelemetry-collector-releases/assets/103997330/cd07a1dd-5902-479b-873f-9b751d35179d)

I've been looking in documentation it seems all windows are compatible , no requirements needed

![image](https://github.com/open-telemetry/opentelemetry-collector-releases/assets/103997330/4d416a51-65c3-44fd-82a9-ce662e2e04df)

If anybody has an idea it would be great thanks

**Comment by atoulme** [comment]
Go 1.21 doesn’t support Windows 2008, which itself is EOL.

**Comment by mx-psi** [comment]
Let's continue the discussion over at open-telemetry/opentelemetry-collector-contrib/issues/30327
