### ISSUE TITLE
Publish images to registries other than Docker Hub

### ISSUE THREAD

**Issue by ldx** [open-telemetry/opentelemetry-collector-releases#49]
Docker Hub has introduced pretty aggressive rate limits. We're trying to migrate our deployments to use either public.ecr.aws or quay.io instead, as trying to pull from Docker Hub fails with 429s frequently.

Any chance the images built here could also be published to other registries?

**Comment by jpkrohling** [comment]
Would GitHub container repository work for you? It would be trivial to implement it, as it wouldn't require any new accounts elsewhere.

**Comment by ldx** [comment]
> Would GitHub container repository work for you? It would be trivial to implement it, as it wouldn't require any new accounts elsewhere.

Absolutely, that's a great option.

**Comment by jpkrohling** [comment]
Would you like to give it a try, @ldx?

**Comment by ldx** [comment]
> Would you like to give it a try, @ldx?

I'm not seeing any public package in the repo, is it some other repo?

**Comment by jpkrohling** [comment]
Not sure I get the question, but we don't have any packages yet, this would be the first.

**Comment by ldx** [comment]
> Not sure I get the question, but we don't have any packages yet, this would be the first.

OIC, sorry, I had the impression there was an image in GHCR that I could test.
