### ISSUE TITLE
exporters: unknown type: "loki"

### ISSUE THREAD

**Issue by alexlionnel** [open-telemetry/opentelemetry-collector-releases#509]
I got an error when i tried to use loki exporter, when i install otel collector using rpm package
I have install otelcol using rpm package
```
sudo yum update
sudo yum -y install wget systemctl
wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.96.0/otelcol_0.96.0_linux_amd64.rpm
sudo rpm -ivh otelcol_0.96.0_linux_amd64.rpm
```
Then i updated the file `/etc/otelcol/config.yaml`, by adding loki exporter
```
exporters:
  debug:
    verbosity: detailed
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
    tls:
      insecure: true
    default_labels_enabled:
      exporter: true
      job: true
```
I restarted the service otelcol
```
sudo systemctl restart otelcol
```
But i got this error
```
* error decoding 'exporters': unknown type: "loki" for id: "loki" (valid values: [debug logging otlphttp opencensus otlp file kafka prometheus prometheusremotewrite zipkin])
2024/03/25 15:40:33 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
```

**Comment by TylerHelmuth** [comment]
The `lokiexporter` is not included in the `otelcol` distribution: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/manifest.yaml.  It is included in the `otelcol-contrib` distribution: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/52c80c07f5a527a80423f01bc3c8c8bf2da68026/distributions/otelcol-contrib/manifest.yaml#L65

**Comment by alexlionnel** [comment]
OK, so what is the command line to install rpm package otel-collector-contrib?

**Comment by atoulme** [comment]
Just use this rpm instead:
https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.96.0/otelcol-contrib_0.96.0_linux_amd64.rpm
