### ISSUE TITLE
Default config path changed in the contrib container image

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-collector-releases#59]
Since `0.42.0` the default `config.yaml` path used in the contrib container image changed from `/etc/otelcol/config.yaml` to `/etc/otelcol-contrib/config.yaml`. 

As far as I understand it was done here: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/43

While I have not found  `/etc/otelcol/config.yaml` in any documentation I imagine that there may be a lot of users relying on this path.

Docker inspect dumps for reference: 
- [0420inspect.txt](https://github.com/open-telemetry/opentelemetry-collector-releases/files/7881531/0420inspect.txt)
- [0400inspect.txt](https://github.com/open-telemetry/opentelemetry-collector-releases/files/7881532/0400inspect.txt)

**Comment by Kielek** [comment]
One more comment, similar breaking change was also introduced between 0.41.0 and 0.42.0

0.41.0: `/etc/otel/config.yaml`
0.42.0: `/etc/otelcol/config.yaml`

For details, please check
https://github.com/open-telemetry/opentelemetry-collector-releases/blob/606b9299551267c8c80c818b057f08a9444458d7/distributions/otelcol/Dockerfile#L19

**Comment by jpkrohling** [comment]
This was an adjustment done to ensure that there can be two distributions running at the same time at the same node.

**Comment by pellared** [comment]
For now, I think that documenting it as part of the changelog is good enough (until there are more complaints)

**Comment by pellared** [comment]
@jpkrohling 

> This was an adjustment done to ensure that there can be two distributions running at the same time at the same node.

Is there any issue where this use-case is described? Seems strange for me especially that `otelcol-contrib` is a superset of `otelcol`. Why would one like to have both distributions in one container? It would only increase the image size, attack-surface etc.

**Comment by jpkrohling** [comment]
Because we might have other, focused distributions running on the same node. For instance, a tracing distribution, a metrics distribution, and a logging distribution. All with the smallest possible set of components for that use-case, with varying degrees of stability expectations (traces are stable, metrics almost, logs not so much).

**Comment by mx-psi** [comment]
I am going to close this, we decided to keep this change, but we should be more careful with similar changes in the future
