### ISSUE TITLE
The 'jaegertracing/all-in-one:latest' is already using version 0.104.0. How can I change host from 'localhost' to '0.0.0.0'?

### ISSUE THREAD

**Issue by horw** [open-telemetry/opentelemetry-collector-releases#596]
Hello!
The latest version of Jaeger already uses 'localhost' instead of '0.0.0.0'. Do you know how I can set up the correct hostname?

**Comment by atoulme** [comment]
I guess you mean the jaegerreceiver, please see its config, with this example. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/jaegerreceiver/README.md?plain=1#L43

Please open issues in -contrib or use StackOverflow to ask questions as this repository is aimed to manage distributions. Closing as unplanned.
