### ISSUE TITLE
Check goreleaser broken in main

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-releases#642]
Something [broke](https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/10406545812/job/28820898937) in main with https://github.com/open-telemetry/opentelemetry-collector-releases/commit/de92512197c429960163d486b55825ef778a1761.  Not sure what happened yet as the PR's CI passed.

**Comment by jackgopack4** [comment]
looks like goreleaser v2.2 deprecated a tag for snapshot; created a draft PR that I will make official if checks pass: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/643
