### ISSUE TITLE
Error Decoding Receivers Unknown Type awscloudwatchmetrics

### ISSUE THREAD

**Issue by amarigny** [open-telemetry/opentelemetry-collector-releases#649]
Hello,

I was looking to use the awscloudwatchmetrics and ran into the below scenario:

Using otel/opentelemetry-collector-contrib:0.107.0 and attempting to use the awscloudwatchmetrics receiver (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscloudwatchmetricsreceiver) gave the following error:

error decoding 'receivers': unknown type: "awscloudwatchmetrics" for id: "awscloudwatchmetrics" (valid values: [expvar influxdb memcached postgresql sapm elasticsearch awsxray googlecloudspanner k8s_events pulsar snowflake sqlquery statsd nop httpcheck otelarrow podman_stats datadog k8sobjects kafka loki namedpipe oracledb journald riak tcplog couchdb opencensus wavefront webhookevent mongodbatlas purefb prometheus_simple splunk_hec nsxt filelog haproxy jaeger sshcheck vcenter windowsperfcounters apachespark active_directory_ds awsfirehose kafkametrics signalfx windowseventlog otlp filestats hostmetrics iis splunkenterprise sqlserver awscloudwatch zookeeper carbon chrony cloudfoundry googlecloudpubsub nginx otlpjsonfile zipkin apache azureblob azuremonitor docker_stats kubeletstats mysql snmp aerospike collectd jmx mongodb purefa rabbitmq udplog azureeventhub awsecscontainermetrics cloudflare prometheus skywalking awscontainerinsightreceiver flinkmetrics fluentforward k8s_cluster receiver_creator redis solace syslog bigip])
Stream closed EOF for otel-collector/testing-opentelemetry-collector-agent-5w5rh (opentelemetry-collector)

Not sure if this is related to the list defined in distributions/otelcol-contrib/manifest.yaml.

**Comment by jpkrohling** [comment]
Dosu is correct, the component isn't there, as it's still under development:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscloudwatchmetricsreceiver

In fact, this component will likely be removed before it's complete, as the development has stalled on that one.
