### ISSUE TITLE
Can not download ocb binary tool

### ISSUE THREAD

**Issue by wooonderful** [open-telemetry/opentelemetry-collector-releases#658]
When I try to download the ocb binary tool as the document fallow:
<img width="927" alt="image" src="https://github.com/user-attachments/assets/d90c621c-cdd2-4281-8dfb-a4b4944d66fa">

I just get a 404 response:
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/4b2d2cfc-082f-4dd2-a6da-590230fd776a">

So when I try to find it in the github release assets, I can't. 
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/d0d870df-9182-42e1-a429-479217664fc3">

**Comment by jpkrohling** [comment]
The actual URL is this: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv0.108.0/ocb_0.108.0_linux_amd64

Here's the release page for ocb: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/cmd%2Fbuilder%2Fv0.108.0

Note that OTel Core is 0.108.1 but the actual binary is 0.108.0.

**Comment by wooonderful** [comment]
ok,thanks.

it is the latest document using the wrong version.

https://opentelemetry.io/docs/collector/custom-collector/#step-1---install-the-builder

**Comment by jpkrohling** [comment]
Likely. Let me transfer this to the docs repo.
