### ISSUE TITLE
Move back to `latest` for goreleaser

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-releases#668]
Because of goreleaser/goreleaser/issues/5138, CI is currently broken when using goreleaser v2.3.0+.

#667 fixes this temporarily for the next release

**Comment by jade-guiton-dd** [comment]
Are we sure we want to move back to latest instead of upgrading the version periodically? Manually upgrading would prevent the CI unexpectedly breaking on main like in #667 and #676.

**Comment by mx-psi** [comment]
Could we automate the bumping? For other stuff like Github Actions we use dependabot/renovate bot, but here I don't think there is an equivalent tool that is ready for this. Maybe we can ask upstream on the goreleaser repositories for advice?

**Comment by mx-psi** [comment]
@mowies Do you have any links/examples explaining how this would be done with renovate?

**Comment by mowies** [comment]
Something like this should work with renovate. It's a [custom regex manager](https://docs.renovatebot.com/modules/manager/regex/) that matches the goreleaser action's input for the version. It could probably be done a little nicer and more resilient but it should work I think.
```
    {
      "fileMatch": [
        "(^|\\/).github\\/.*\\.ya?ml$"
      ],
      "matchStrings": [
        "goreleaser\\/goreleaser-action@[\\S\\s]+version: (?<currentValue>.*?)$"
      ],
      "depName": "github.com/goreleaser/goreleaser",
      "datasourceTemplate": "github-releases"
    }
```

**Comment by mowies** [comment]
@mx-psi if you could take of setting up renovate in this repo, then i'd be happy to contribute the needed config changes :)

**Comment by mx-psi** [comment]
I believe you will have to file an issue similar to this one: open-telemetry/community/issues/1792 but for this repository. I am happy to voice my support in such an issue.

**Comment by mowies** [comment]
Cool! I filed the issue: https://github.com/open-telemetry/community/issues/2403

**Comment by mx-psi** [comment]
Done!

**Comment by mowies** [comment]
PR is open for this: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/728

**Comment by mowies** [comment]
seems like the regex I added still has some issues. I'll do a follow up PR

**Comment by mowies** [comment]
@mx-psi maybe this PR fixes it: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/733

**Comment by mx-psi** [comment]
Was this fixed by #733?

**Comment by mowies** [comment]
unfortunately not, but i pivoted to test everything on my own fork with renovate activated there, so the next one will stick 😅

**Comment by mowies** [comment]
Ok I think I fixed it now :)
https://github.com/open-telemetry/opentelemetry-collector-releases/pull/737

**Comment by mowies** [comment]
![Screenshot 2024-11-20 at 12 34 03](https://github.com/user-attachments/assets/50128758-0fa6-4897-80ed-37cd8d969e2d)
looks like this is actually solved now
