### ISSUE TITLE
Container image doesn't export http receiver 4318

### ISSUE THREAD

**Issue by abraxxa** [open-telemetry/opentelemetry-collector-releases#692]
The Perl OpenTelemetry::Exporter::OTLP module currently only supports the http protocol and not grpc.
The [config](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/config.yaml#L17) enables the http receiver but the [Dockerfile](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/Dockerfile#L14) doesn't expose it.
Why?

**Comment by mowies** [comment]
the dockerfile `EXPOSE` statement is more for documentation than anything else (see [dockerfile docs](https://docs.docker.com/reference/dockerfile/#expose)). So it doesn't actually impact whatever the collector listens to in the container.

But I agree that it should still be aligned for consistency.

**Comment by abraxxa** [comment]
FYI the Docker Desktop UI lets you only expose ports that are specified in the Dockerfile with EXPOSE. Using the CLI was my workaround.

**Comment by mowies** [comment]
Ah ok I'm not that familiar with the UI :)
Then it should definitely be updated

**Comment by mx-psi** [comment]
@abraxxa would you be willing to file a PR for this? We can help you get it into the right shape so we can merge it :)

**Comment by abraxxa** [comment]
I think the time you spend on reviewing the PR is about the same as if you commit it yourself ;-)
But if you want it for some other reason I can do it.

**Comment by mx-psi** [comment]
> I think the time you spend on reviewing the PR is about the same as if you commit it yourself ;-) But if you want it for some other reason I can do it.

Just wanted to encourage to contribute yourself :smile: no other reason

**Comment by mowies** [comment]
i can do it as well 🤷🏼

**Comment by mowies** [comment]
@abraxxa @mx-psi PR is open
