### ISSUE TITLE
Not tracking multiple HTTP endpoints proerply 

### ISSUE THREAD

**Issue by Samarth007-2002** [open-telemetry/opentelemetry-collector-releases#706]
I have refrenced the blog and did everything .
It collects metrics but the output only gives 1 single line and the name is "A" instead of "the url link" ; I have 5 endpoints setup
and also the value is 0.2 instead of 0 or 1.

![image](https://github.com/user-attachments/assets/183fce2e-ff7d-4e77-a45c-9cc65f6d8bd3)

**Comment by jpkrohling** [comment]
This is very likely the wrong repository for this question. I'm closing this, with the recommendation that you ask this via Slack. Don't forget to mention what's the blog post you are following, what you expect to see, and what you are seeing instead.
