### ISSUE TITLE
Add Goreleaser templating logic for more distributions (i.e. otelcol-k8s, otelcol-otlp)

### ISSUE THREAD

**Issue by jackgopack4** [open-telemetry/opentelemetry-collector-releases#716]
currently, only the otelcol and otelcol-contrib goreleaser files are generated via template.
There are some differences between these and the k8s and otlp distros; specifically having to do with fewer versions and/or different default files included.
Given that our goreleaser templates are run in cmd/goreleaser, there should be some logic to enable generating the k8s and otlp distributions (and any future distributions) with this template.
I'm happy to take this on, as it may be necessary to split up goreleaser further to enable `buildmode=pie` for security in accordance with https://github.com/open-telemetry/opentelemetry-collector-releases/issues/618 and https://github.com/open-telemetry/opentelemetry-collector-releases/issues/693

**Comment by mx-psi** [comment]
Sounds reasonable to me

**Comment by mowies** [comment]
@jackgopack4 i guess this can be closed since the PR is merged?
