### ISSUE TITLE
`latest` tag not updated 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-releases#73]
The [latest](https://hub.docker.com/layers/otel/opentelemetry-collector/latest/images/sha256-cec18c72535bebeaca3615e841b19066b468f87a2e29b724b118b5b7bf8808ce?context=explore) tag in dockerhub isn't getting updated during the release process. This is causing user confusion.

**Comment by codeboten** [comment]
> Can we remove it? I've never been a fan of using mutable tags in this manner.

I'm not a fan of it either, but people (myself included) do use them and we've already been publishing it. I would prefer we keep it updated moving forward.

**Comment by mhellsten-ml** [comment]
This is still an issue. Having the "latest" tag point the latest stable release is Docker community standard, so I don't think this is just a matter of preference or style. People who don't want to pull the latest when they relaunch would/should use a version-specific tag. Thanks.

**Comment by delanym** [comment]
Delete it, let the 2 people (or was it 3?) who still rely on this old tag for their mission critical telemetry systems (is there such a thing?) quickly fix the issue, and we can all get on with our lives.
Having an invalid tag hanging around confusing everyone is worse.

**Comment by mhellsten-ml** [comment]
> Delete it, let the 2 people (or was it 3?) who still rely on this old tag for their mission critical telemetry systems (is there such a thing?) quickly fix the issue, and we can all get on with our lives. Having an invalid tag hanging around confusing everyone is worse.

This isn't for production so much as development: People who throw up a local stack of supporting services typically expect to get the latest stable release on the latest tag. When the behavior of the container that comes up doesn't match the documentation it's very confusing. 2 or 3 people commenting on this issue doesn't mean it's the entire  universe of people this affects.

**Comment by dyladan** [comment]
This is causing active confusion with users. Either fix the tag or remove it but leaving it broken is misleading and the worst of both worlds. `latest` tag is a docker community idiom that many (most?) users not only expect to work but are frustrated when it doesn't. I very often use the `latest` tag of docker images as a branch in integration tests so that we can catch issues without having to manually modify the version matrix.

**Comment by bogdandrutu** [comment]
Updated the latest tag to 0.56.0, using manifest and image group as the base tag.

**Comment by giuliohome** [comment]
**This is causing a terrible confusion!!!**
