### ISSUE TITLE
Enable merge queue on this repository

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-releases#750]
We have wanted to enable a merge queue in opentelemetry-collector-contrib for some time now. To test it out first and remove any wrinkles, we want to roll this out on smaller repositories like opentelemetry-collector-releases first. To do that we would need to?:
1. File a PR like open-telemetry/opentelemetry-collector-contrib/pull/31162 on this repository
2. File an issue on the community repo similar to this one: open-telemetry/community/issues/1936

**Comment by ArthurSens** [comment]
I'm looking at the [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) and the example you provided now. For this repository, do I understand correctly that all workflows in [this folder](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/.github/workflows) should be added to the merge queue? Or is there any workflow that we can ignore?

**Comment by mx-psi** [comment]
@ArthurSens I think for this repository anything with a trigger on pull requests or pushes to main should be in the merge group as well. So for example [this one](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/6337595c0362f6a68bcf4885ac0cf1431e9816b8/.github/workflows/base-ci-goreleaser.yaml#L4) should not be added and [this one](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/6337595c0362f6a68bcf4885ac0cf1431e9816b8/.github/workflows/release-contrib.yaml#L3-L4) should not be added either since they are triggered manually/with a tag push

**Comment by mx-psi** [comment]
Will close when open-telemetry/community/issues/2457 is done

**Comment by ArthurSens** [comment]
And now this one should be good to close as well :)
