### ISSUE TITLE
Create follow up issue when nightly tests fail

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-releases#756]
How will we be able to tell if there is an error? I think we should create a `release:blocker` issue if there is a failed test. We can do this in a follow up PR if you want to.

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-collector-releases/pull/666#discussion_r1860502491_

**Comment by mowies** [comment]
The issue should ideally be created in -contrib, if that's not possible then in -releases

**Comment by mowies** [comment]
pls assign this to me :)
