### ISSUE TITLE
`exec: no such file or directory` on v0.116.0 images

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-collector-releases#783]
Hi, running the latest images for the collector and contrib gives the following errors:

collector:

```
$ docker run --rm otel/opentelemetry-collector:latest
Unable to find image 'otel/opentelemetry-collector:latest' locally
latest: Pulling from otel/opentelemetry-collector
8f7858a9e10a: Download complete 
25b3dbd41aa1: Download complete 
1ab3cc28ef42: Download complete 
Digest: sha256:91d0e8dcd0cf4c0f2b1002a3be5979dfb20be235af96ef51063164548e2ccff6
Status: Downloaded newer image for otel/opentelemetry-collector:latest
exec /otelcol: no such file or directory
```
contrib:

```
$ docker run --rm otel/opentelemetry-collector-contrib:latest
Unable to find image 'otel/opentelemetry-collector-contrib:latest' locally
latest: Pulling from otel/opentelemetry-collector-contrib
786f0d5741dd: Download complete 
1ae9138cffe0: Download complete 
93f09e4df467: Download complete 
Digest: sha256:70217a89d27c678ead44f196d80aa8c2717cb68d0301dbdc40331dbec0a3e605
Status: Downloaded newer image for otel/opentelemetry-collector-contrib:latest
exec /otelcol-contrib: no such file or directory
```

**Comment by TylerHelmuth** [comment]
@jackgopack4 could https://github.com/open-telemetry/opentelemetry-collector-releases/pull/726 be the culprit?

**Comment by MrAlias** [comment]
Just for reference, this seems to be affecting GitHub actions uses this container as well: https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/12377825359/job/34549117158?pr=1431

**Comment by jackgopack4** [comment]
This combined with the refactor ticket means we should probably go back to the drawing board on the PIE mode build. Apologies as I am out of office for the next week or two.

**Comment by CodeBlanch** [comment]
We ran into this as well over on OpenTelemetry .NET. Our OtlpExporter integration tests (which use [otel/opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-dotnet/blob/c3bb89ae5011926294e86796089c34ab6d4c350f/test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/IntegrationTest/docker-compose.yml#L24)) are blowing up: https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/12379183379/job/34553658657?pr=6032#step:3:239

**Comment by jackgopack4** [comment]
It was supposed to be internal linking but I guess that didn't get configured properly?

**Comment by songy23** [comment]
New images 0.116.1 have been pushed, I tested with `docker run --rm otel/opentelemetry-collector:0.116.1` it's working fine.

**Comment by alorenzo175** [comment]
The `otel/opentelemetry-collector-builder:0.116.0` has the same issue (`exec /usr/local/bin/ocb: no such file or directory`), and I don't see any `0.116.1` tag. Maybe it was missed in the update to 0.116.1?
