### ISSUE TITLE
Run all release builds on PRs

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-releases#85]
Currently, CI for PRs on this repository does not build all the artifacts. This makes it hard to catch issues before actually tagging a release. To prevent this we can do a gorelease [dry run](https://goreleaser.com/quick-start/?h=dry+r#dry-run) on all PRs.

**Comment by mx-psi** [comment]
This would need to be modified here https://github.com/open-telemetry/opentelemetry-collector-releases/blob/b619070ca9ab3ad41be7754a5cad722f53104964/.github/workflows/ci-goreleaser.yaml#L43

**Comment by jpkrohling** [comment]
I think it might be better to have a nightly build, trying the current tip of the main branches from contrib and core. Running go-releaser would still make sense for PRs touching the go-releaser config.

Was the 386 problem caused by a new component, or by a change in an existing component?

**Comment by mx-psi** [comment]
> I think it might be better to have a nightly build, trying the current tip of the main branches from contrib and core. Running go-releaser would still make sense for PRs touching the go-releaser config.

That also sounds like a good idea

> Was the 386 problem caused by a new component, or by a change in an existing component?

It was caused by a bump on the github.com/open-telemetry/opentelemetry-log-collection dependency, which is used by many (all?) log receivers

**Comment by jpkrohling** [comment]
> It was caused by a bump on the github.com/open-telemetry/opentelemetry-log-collection dependency, which is used by many (all?) log receivers

So, it means that unless we had a change on this repo, we wouldn't have caught this in time. A periodic/daily build would probably have caught this, except if the bug was introduced less than 24h before the release.

**Comment by mx-psi** [comment]
My point (and I think @Aneurysm9's probably is too) is that if we run it on PRs we would have caught it before merging https://github.com/open-telemetry/opentelemetry-collector-releases/pull/81, and we would have avoided the tag-then-untag hack. I don't know if running in *all* PRs is the right answer, but at least on release-related PRs it should definitely do a full dry run.

**Comment by Aneurysm9** [comment]
Yes, perhaps we don't need to run the full process on every PR, but certainly any PR that changes the builder manifests or goreleaser config.

**Comment by jpkrohling** [comment]
> any PR that changes the builder manifests or goreleaser config

We have an agreement here. Indeed, we should run the builds when the manifests have changed as well.
