### ISSUE TITLE
How to enter collector docker container

### ISSUE THREAD

**Issue by yangtaoran** [open-telemetry/opentelemetry-collector-releases#86]
I pull `otel/opentelemetry-collector` image from docker hub, then I  use `docker run -it --rm -d -p 4371:4371 otel/opentelemetry-collector:latest` command to run it with a container.
But I cannot enter to the running cntainer, my commands like this:
`docker exec -it c21e411918ae2acd5b3fffb06b394fcfa90e8f2c96c6ed3d63e5c8a5f1ff0bc6 sh`
`docker exec -it c21e411918ae2acd5b3fffb06b394fcfa90e8f2c96c6ed3d63e5c8a5f1ff0bc6 /bin/sh`
`docker exec -it c21e411918ae2acd5b3fffb06b394fcfa90e8f2c96c6ed3d63e5c8a5f1ff0bc6 bash`
`docker exec -it c21e411918ae2acd5b3fffb06b394fcfa90e8f2c96c6ed3d63e5c8a5f1ff0bc6 /bin/bash`
the error like this:
`OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown`

**Comment by mx-psi** [comment]
On Kubernetes one can use the beta command [`kubectl debug`](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container) to debug containers without a shell, but maybe we want to have non-scratch containers for people who use containers without Kubernetes.

**Comment by jpkrohling** [comment]
Either that, or have debug images. We have such for Jaeger, with delve also available, so that people can attach debuggers to the container.

**Comment by pavolloffay** [comment]
I would vote to have a small image with a shell.

**Comment by jpkrohling** [comment]
I'm closing, as the demand for this isn't apparently that high and `kubectl debug` seems to do the trick.
