### ISSUE TITLE
Can not start service after installed on Azure VM Ubuntu. 

### ISSUE THREAD

**Issue by aixasz** [open-telemetry/opentelemetry-collector-releases#87]
**Describe the bug**
This issue occurred only Azure VM Linux (Ubuntu). 
After installed service couldn't started.
```console
root@telemetry-machine:/home/telemetry# systemctl start otelcol.service
root@telemetry-machine:/home/telemetry# systemctl status otelcol.service
otelcol.service - OpenTelemetry Collector
    Loaded: loaded (/usr/lib/systemd/system/otelcol.service, enabled)
    Active: failed (failed)
```

**Steps to reproduce**
Use azure VM Linux and install `otelcol` following [this document](https://opentelemetry.io/docs/collector/getting-started/#linux-packaging). 

**What did you see instead? **

```console
(Reading database ... 190438 files and directories currently installed.)
Preparing to unpack otelcol_0.44.0_linux_amd64.deb ...
Unpacking otelcol (0.44.0) over (0.44.0) ...
Setting up otelcol (0.44.0) ...
dpkg: error processing package otelcol (--install):
 installed otelcol package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 otelcol
```

**What version did you use? **
Version: 0.44.0

**What config did you use? **
Config: just default configuration file.

**Environment**
```console
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by jpkrohling** [comment]
This puzzled me for a while, and it looks like we were bitten by https://github.com/goreleaser/goreleaser/pull/2910. I'll open a PR shortly changing the location of the binaries. In the meantime, users are advised to copy the unit file into a user-space location, like `/etc/systemd/system` and adjust the ExecStart entry to the appropriate path.

**Comment by rubenruizdegauna** [comment]
Thanks @jpkrohling !
